// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDktnDsWsdNvguE88DIprX6xcXJI_lnXio',
    appId: '1:412319594062:web:7b5f6de0b1bc947ffe751f',
    messagingSenderId: '412319594062',
    projectId: 'flutter-chat-app-c6bc4',
    authDomain: 'flutter-chat-app-c6bc4.firebaseapp.com',
    storageBucket: 'flutter-chat-app-c6bc4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKmwUQrb0E_CKivWCMjRHb4bUzCaCX8Fg',
    appId: '1:412319594062:android:5b4a3dd0b75ccd49fe751f',
    messagingSenderId: '412319594062',
    projectId: 'flutter-chat-app-c6bc4',
    storageBucket: 'flutter-chat-app-c6bc4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJFhiDPB_KfK4Cz2pVh_6KElW6tKfdM9I',
    appId: '1:412319594062:ios:99083113329155edfe751f',
    messagingSenderId: '412319594062',
    projectId: 'flutter-chat-app-c6bc4',
    storageBucket: 'flutter-chat-app-c6bc4.firebasestorage.app',
    iosBundleId: 'com.chatapp.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJFhiDPB_KfK4Cz2pVh_6KElW6tKfdM9I',
    appId: '1:412319594062:ios:99083113329155edfe751f',
    messagingSenderId: '412319594062',
    projectId: 'flutter-chat-app-c6bc4',
    storageBucket: 'flutter-chat-app-c6bc4.firebasestorage.app',
    iosBundleId: 'com.chatapp.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDktnDsWsdNvguE88DIprX6xcXJI_lnXio',
    appId: '1:412319594062:web:e2c7a2443f0c4a40fe751f',
    messagingSenderId: '412319594062',
    projectId: 'flutter-chat-app-c6bc4',
    authDomain: 'flutter-chat-app-c6bc4.firebaseapp.com',
    storageBucket: 'flutter-chat-app-c6bc4.firebasestorage.app',
  );
}
